import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/Navbar'
import Footer from '@/components/Footer'
import AutProvider from '@/components/AutProvider'
import SidebarProvider from '@/contexts/SidebarContext'
import Sidebar from '@/components/Sidebar'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'EddyDev',
  description: 'Generated by EddyDev',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SidebarProvider>
          <AutProvider>
            <div className='flex flex-col justify-between w-full min-h-screen transition-all duration-300'>
              <Sidebar />
              <Navbar />
                {children}
              <Footer />
            </div>
          </AutProvider>
        </SidebarProvider>
      </body>
    </html>
  )
}
